### ISSUE TITLE
[FEATURE] [GET] 친구 닉네임 검색

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/back-end#12]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 닉네임으로 친구 검색하는 API 작성

## TODO

- [x] 브랜치 생성
- [x] 사용자 목록에서 닉네임 조회 쿼리문 작성 -> '%조회할 닉네임%'으로 검색하도록
