### ISSUE TITLE
[FEATURE] [POST] 댓글 작성

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#13]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비내역에 댓글을 새로 작성하는 api

## TODO

- [x] comment 데이터베이스에 사용자가 새로 추가하는 댓글의 정보 추가하는 기능
- [x] 댓글과 대댓글의 추가의 기능 구분 여부를 고민해보자
