### ISSUE TITLE
[FEATURE] [GET] 총 지출 조회

### ISSUE THREAD

**Issue by jaehuiLee** [sobeeLOG/back-end#22]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [x] 날짜 기준으로 총 지출 내역 합산하기
