### ISSUE TITLE
[FEATURE] [PUT] 댓글 수정

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#25]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 작성되어 있는 댓글을 수정하는 기능

## TODO

- [x] 수정된 content를 댓글 데이터베이스에 적용하기
