### ISSUE TITLE
[FEATURE] [PATCH] 친구 신청 수락

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/back-end#28]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 들어온 친구 신청을 수락하는 기능 

## TODO

- [x] 브랜치 생성
- [x] 친구 테이블에서 2개의 로우 수정
- [x] DB 확인
