### ISSUE TITLE
[FEATURE] [POST] 좋아요/싫어요 공감하기

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#29]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비 내역 게시글에 좋아요/ 싫어요 표시를 남기는 api

## TODO

- [x] 사용자가 게시글에 표시한 좋아요/ 싫어요를 데이터베이스에 POST
- [x] 사람 1명 당 좋아요/ 싫어요 1번만 가능하게 구현해보자
