### ISSUE TITLE
[FEATURE] [GET] 월별 캘린더 조회

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/back-end#3]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 월별로 소비내역이 있는 날의 Date값을 리스트로 반환하는 api
- 월별로 댓글이나 반응이 있는 날의 Date값을 리스트로 반환하는 api

## TODO

- [ ] 소비내역이 있는 날을 월별로 구분해내는 방법 고민(date parsing) -> 중복 date 값 처리
- [ ] 댓글이나 반응이 있는 날을 어떤 기준의 순서대로 적용해서 리스트로 반환할 것인지 고민
