### ISSUE TITLE
[FEATURE] [GET] 일별 소비내역 조회 

### ISSUE THREAD

**Issue by jaehuiLee** [sobeeLOG/back-end#4]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 일별로 소비내역이 있는 날의 Date 값을 리스트로 반환하는 api
- 일별로 댓글이나 반응이 있는 날의 Date 값을 리스트로 반환하는 api

## TODO

- [ ] type(simple/detail)별로 받아오는 데이터 고민
- [ ] 그냥 고민...
