### ISSUE TITLE
[FEATURE] [POST] 대댓글을 작성할 때 부모 댓글이 대댓글인지 확인하는 기능

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#40]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 대댓글을 작성할 때 부모 댓글이 대댓글인지 확인하는 if문

## TODO

- [ ] 부모 댓글의 정보 가져오기
- [ ] 부모 댓글의 replyID가 NULL인지 확인하기
