### ISSUE TITLE
[BUG] 친구 신청이 중복으로 들어가는 문제 

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/back-end#43]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 이미 친구이거나 친구 신청이 된 경우에도 친구 요청이 되어 DB 오류 발생

## TODO

- [ ] 친구 삭제 기능 구현할 때 작성한 친구 ID 받아오는 함수를 친구 신청 로직에 추가하기
- [ ] 추가로 "내친구 목록 보기", "친구 찾기" 기능에서 서버 오류 응답 메시지 반환 작업도 같이 추가하겠음
