### ISSUE TITLE
[FEATURE] [POST] 소비내역 작성

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/back-end#45]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 날짜 포함한 소비내역 post 하기

## TODO

- [ ] 날짜없이 post 되는 api 변경
- [ ] api 테스트 진행
