### ISSUE TITLE
[FEATURE] [GET] 소비내역 아이디별 조회 기능

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/back-end#48]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 아이디별 소비내역 조회 기능 추가, 이미 있는 GetConsumption 변경 예정

## TODO

- [ ] where절에 조건 추가
