### ISSUE TITLE
[BUG] 이모티콘 post api 로직 수정 및 GET api 추가

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/back-end#50]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요

- 이모티콘 수정이 불가능한 로직 파악
- 이모티콘 수정 및 조회 로직 추가

## TODO

- [ ] 로직 변경 필요 + 이모티콘 데이터 타입 처리 필요
- [ ] 이모티콘 수정시 기존 내용은 삭제 후 추가하는 처리 필요
