### ISSUE TITLE
[BUG] 좋아요/ 싫어요 이모티콘 관련 수정

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#55]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 소비내역을 get할 때 이모티콘의 수를 가져오는 부분에서 좋아요/ 싫어요의 수가 무조건 같게 나온다.
- emticonDELETE 기능 확인해봐야 할 것 같음

## TODO

- [x] getCountOfEmoticon 수정
- [x] emticonDELETE 내용 확인 및 수정
