### ISSUE TITLE
[BUG] 사용자 검색 결과에 친구인 사용자 제외

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/back-end#57]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 기존: 닉네임에 키워드가 포함된 사용자를 모두 검색
- 이미 친구이거나 친구 신청을 보낸 사용자도 검색 결과에 포함되어 친구 신청이 들어가는 오류 발생
- findUserListGET 파일 수정

## TODO

- [ ] 친구 테이블에 있는지 확인하는 로직 추가
