### ISSUE TITLE
[FEATURE] [GET] 소비 내역의 전체 댓글 조회

### ISSUE THREAD

**Issue by seyoung-Han-ouo** [sobeeLOG/back-end#6]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 댓글을 볼 소비내역과 관련된 comment의 데이터(commentID, userID, content, date, replyID, isDelete)들을 반환하는 api

## TODO

- [x] 소비 내역의 c_historyID로 이에 해당하는 comment 데이터 가져오기
- [x] 가져온 comment 데이터들을 replyID가 null인 것과 아닌 것을 서로 다른 리스트로 반환할지 고민
