### ISSUE TITLE
[FEATURE] [GET] 친구 소비내역 피드 조회

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/back-end#9]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 친구 소비내역 조회 api 작성

## TODO

- [x] 브랜치 파기
- [x] 친구 소비내역 조회 쿼리문 작성
- [x] 데이터 반환시 구조 고려하기
- [x] 고려해야할 점 : 친구 관계 파악, 친구 소비내역 공개 여부, 댓글, 이모티콘 조회 방식(따로 api 작성하는게 좋을 듯, 나중을 생각해서)
